server:
  port: 8080
  servlet:
    context-path: /CRUD
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///imooc
    username: root
    password: xc19961016
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: i18n.login
#    禁用缓存
  thymeleaf:
    cache: false